# Generated by Django 5.1.7 on 2025-03-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_meter_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="day_kwh",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reading",
            name="night_kwh",
            field=models.IntegerField(),
        ),
    ]
