# Generated by Django 5.1.7 on 2025-03-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_reading_day_kwh_alter_reading_night_kwh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
