# Generated by Django 5.1.7 on 2025-03-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_reading_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
