# Generated by Django 5.1.7 on 2025-03-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_bill_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reading",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
