# Generated by Django 5.1.7 on 2025-03-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_bill_date_alter_reading_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.user"
            ),
        ),
    ]
